language: java
jdk:
  - openjdk11
services:
  - docker
addons:
  sonarcloud:
    organization: "cahriboom"
    token:
      secure: "**************************" # encrypted value of your token
    
before_install:
  - cd project9/docker/dev/
  - docker-compose up -d

before_script:
  - cd ../../src
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cahriBoom_project9-myerp

after_script:
 - cd ../docker/dev
 - docker-compose stop
 - docker-compose rm -f
 - docker-compose up -d
 - cd ../../src

after_success:
 - mvn --file pom.xml cobertura:cobertura coveralls:report -P test-consumer,test-business
