language: java
jdk:
  - openjdk11
sudo: false
services:
  - docker
addons:
  sonarcloud:
    organization: "cahriboom"
before_script:
   - docker-compose -f project9/docker/dev/docker-compose.yml up -d
script:
  - mvn --file ./src/pom.xml clean jacoco:prepare-agent package jacoco:report coveralls:report -P test-consumer,test-business
after_script:
  - mvn clean test jacoco:report coveralls:report
  - docker-compose -f project9/docker/dev/docker-compose.yml stop
  - docker-compose -f project9/docker/dev/docker-compose.yml rm -f
