language: java
jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: "cahriboom"
before_script:
  - cd project9/docker/dev/
  - docker-compose up -d
  - cd ../../src
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn -f ./project9/src/pom.xml
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonal:sonal -Dsonar.projectKey=cahriBoom_project9-myerp
after_script:
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
