language: java
jdk:
  - openjdk11
sudo: false
services:
  - docker
addons:
  sonarcloud:
    organization: "cahriboom"
before_script:
  - cd project9/docker/dev/
  - docker-compose up -d
  - cd ../../src
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn --file ./src/pom.xml clean jacoco:prepare-agent package jacoco:report coveralls:report -P test-consumer,test-business
  
after_script:
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
