language: java
jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: "cahriboom"
before_script:
  - cd project9/docker/dev/
  - docker-compose up -d
  - cd ../../src
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn plugin-prefix:goal
  - mvn plugin-group-id:plugin-artifact-id[:plugin-version]:goal
  - mvn test
  - mvn clean -P test-consumer,test-business org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cahriBoom_project9-myerp-Dsonar.login=p8W591YxV1JxE1kvSdCHrA
after_script:
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -f
