  
language: java
jdk:
  - openjdk8
services:
  - docker
addons:
  sonarcloud:
    organization: "cahriboom"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonal:sonal -Dsonar.projectKey=cahriBoom_project9-myerp
